pipeline {
    agent any

    environment {
        DEPLOY_PATH = "{{deploy-path}}"
    }

    stages {

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                  sh 'npm install'
                }
            }
        }

        stage('Build Angular App') {
            steps {
                dir('frontend') {
                  sh 'ng build --configuration=development'
                }
            }
        }

        stage('Deploy to Nginx') {
            steps {
                sh '''
                rm -rf $DEPLOY_PATH/*
                cp -r dist/OPEN_SOURCE_FL/* $DEPLOY_PATH/
                '''
            }
        }
    }
}
