export const contries = [
    { name: "Afghanistan", iso2: "AF" },
    { name: "Albania", iso2: "AL" },
    { name: "Algeria", iso2: "DZ" },
    { name: "Andorra", iso2: "AD" },
    { name: "Angola", iso2: "AO" },
    { name: "Argentina", iso2: "AR" },
    { name: "Armenia", iso2: "AM" },
    { name: "Australia", iso2: "AU" },
    { name: "Austria", iso2: "AT" },
    { name: "Azerbaijan", iso2: "AZ" },
    { name: "Bahamas", iso2: "BS" },
    { name: "Bahrain", iso2: "BH" },
    { name: "Bangladesh", iso2: "BD" },
    { name: "Belarus", iso2: "BY" },
    { name: "Belgium", iso2: "BE" },
    { name: "Belize", iso2: "BZ" },
    { name: "Benin", iso2: "BJ" },
    { name: "Bhutan", iso2: "BT" },
    { name: "Bolivia", iso2: "BO" },
    { name: "Bosnia and Herzegovina", iso2: "BA" },
    { name: "Botswana", iso2: "BW" },
    { name: "Brazil", iso2: "BR" },
    { name: "Bulgaria", iso2: "BG" },
    { name: "Cambodia", iso2: "KH" },
    { name: "Cameroon", iso2: "CM" },
    { name: "Canada", iso2: "CA" },
    { name: "Chile", iso2: "CL" },
    { name: "China", iso2: "CN" },
    { name: "Colombia", iso2: "CO" },
    { name: "Costa Rica", iso2: "CR" },
    { name: "Croatia", iso2: "HR" },
    { name: "Cuba", iso2: "CU" },
    { name: "Cyprus", iso2: "CY" },
    { name: "Czech Republic", iso2: "CZ" },
    { name: "Denmark", iso2: "DK" },
    { name: "Dominican Republic", iso2: "DO" },
    { name: "Ecuador", iso2: "EC" },
    { name: "Egypt", iso2: "EG" },
    { name: "Estonia", iso2: "EE" },
    { name: "Ethiopia", iso2: "ET" },
    { name: "Finland", iso2: "FI" },
    { name: "France", iso2: "FR" },
    { name: "Germany", iso2: "DE" },
    { name: "Ghana", iso2: "GH" },
    { name: "Greece", iso2: "GR" },
    { name: "Guatemala", iso2: "GT" },
    { name: "Haiti", iso2: "HT" },
    { name: "Honduras", iso2: "HN" },
    { name: "Hungary", iso2: "HU" },
    { name: "Iceland", iso2: "IS" },
    { name: "India", iso2: "IN" },
    { name: "Indonesia", iso2: "ID" },
    { name: "Iran", iso2: "IR" },
    { name: "Iraq", iso2: "IQ" },
    { name: "Ireland", iso2: "IE" },
    { name: "Israel", iso2: "IL" },
    { name: "Italy", iso2: "IT" },
    { name: "Japan", iso2: "JP" },
    { name: "Jordan", iso2: "JO" },
    { name: "Kazakhstan", iso2: "KZ" },
    { name: "Kenya", iso2: "KE" },
    { name: "Kuwait", iso2: "KW" },
    { name: "Kyrgyzstan", iso2: "KG" },
    { name: "Laos", iso2: "LA" },
    { name: "Latvia", iso2: "LV" },
    { name: "Lebanon", iso2: "LB" },
    { name: "Libya", iso2: "LY" },
    { name: "Lithuania", iso2: "LT" },
    { name: "Luxembourg", iso2: "LU" },
    { name: "Malaysia", iso2: "MY" },
    { name: "Maldives", iso2: "MV" },
    { name: "Mali", iso2: "ML" },
    { name: "Malta", iso2: "MT" },
    { name: "Mexico", iso2: "MX" },
    { name: "Moldova", iso2: "MD" },
    { name: "Mongolia", iso2: "MN" },
    { name: "Morocco", iso2: "MA" },
    { name: "Myanmar", iso2: "MM" },
    { name: "Nepal", iso2: "NP" },
    { name: "Netherlands", iso2: "NL" },
    { name: "New Zealand", iso2: "NZ" },
    { name: "Nigeria", iso2: "NG" },
    { name: "North Korea", iso2: "KP" },
    { name: "Norway", iso2: "NO" },
    { name: "Oman", iso2: "OM" },
    { name: "Pakistan", iso2: "PK" },
    { name: "Panama", iso2: "PA" },
    { name: "Paraguay", iso2: "PY" },
    { name: "Peru", iso2: "PE" },
    { name: "Philippines", iso2: "PH" },
    { name: "Poland", iso2: "PL" },
    { name: "Portugal", iso2: "PT" },
    { name: "Qatar", iso2: "QA" },
    { name: "Romania", iso2: "RO" },
    { name: "Russia", iso2: "RU" },
    { name: "Saudi Arabia", iso2: "SA" },
    { name: "Serbia", iso2: "RS" },
    { name: "Singapore", iso2: "SG" },
    { name: "Slovakia", iso2: "SK" },
    { name: "Slovenia", iso2: "SI" },
    { name: "Somalia", iso2: "SO" },
    { name: "South Africa", iso2: "ZA" },
    { name: "South Korea", iso2: "KR" },
    { name: "Spain", iso2: "ES" },
    { name: "Sri Lanka", iso2: "LK" },
    { name: "Sudan", iso2: "SD" },
    { name: "Sweden", iso2: "SE" },
    { name: "Switzerland", iso2: "CH" },
    { name: "Syria", iso2: "SY" },
    { name: "Taiwan", iso2: "TW" },
    { name: "Tajikistan", iso2: "TJ" },
    { name: "Tanzania", iso2: "TZ" },
    { name: "Thailand", iso2: "TH" },
    { name: "Tunisia", iso2: "TN" },
    { name: "Turkey", iso2: "TR" },
    { name: "Turkmenistan", iso2: "TM" },
    { name: "Uganda", iso2: "UG" },
    { name: "Ukraine", iso2: "UA" },
    { name: "United Arab Emirates", iso2: "AE" },
    { name: "United Kingdom", iso2: "GB" },
    { name: "United States", iso2: "US" },
    { name: "Uruguay", iso2: "UY" },
    { name: "Uzbekistan", iso2: "UZ" },
    { name: "Venezuela", iso2: "VE" },
    { name: "Vietnam", iso2: "VN" },
    { name: "Yemen", iso2: "YE" },
    { name: "Zambia", iso2: "ZM" },
    { name: "Zimbabwe", iso2: "ZW" }
];